# Generated by Django 5.1.2 on 2024-10-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0003_reply_parent_reply_slug_reply_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
